// Date: 03-Jun-18 7:33:39 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.ianRJ.ianMCmod.mobStuffz;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class PersonMob extends ModelBase
{
  //fields
    ModelRenderer leg_right;
    ModelRenderer leg_left;
    ModelRenderer body;
    ModelRenderer head;
    ModelRenderer arm_left;
    ModelRenderer arm_right;
  
  public PersonMob()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      //leg_right.mirror = true;
      leg_right = new ModelRenderer(this, 0, 16);
      leg_right.addBox(0F, 0F, -2F, 4, 12, 4);
      leg_right.setRotationPoint(0F, 12F, 0F);
      leg_right.setTextureSize(64, 32);
      //leg_right.mirror = true;
      setRotation(leg_right, 0F, 0F, 0F);
      leg_right.mirror = false;
      leg_left = new ModelRenderer(this, 0, 16);
      leg_left.addBox(-4F, 0F, -2F, 4, 12, 4);
      leg_left.setRotationPoint(0F, 12F, 0F);
      leg_left.setTextureSize(64, 32);
      leg_left.mirror = true;
      setRotation(leg_left, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(0F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(-4F, 0F, 0F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -20F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 12F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      //arm_left.mirror = true;
      arm_left = new ModelRenderer(this, 40, 16);
      arm_left.addBox(-4F, 0F, -2F, 4, 12, 4);
      arm_left.setRotationPoint(-4F, 0F, 0F);
      arm_left.setTextureSize(64, 32);
      arm_left.mirror = true;
      setRotation(arm_left, 0F, 0F, 0F);
      //arm_right.mirror = false;
      arm_right = new ModelRenderer(this, 40, 16);
      arm_right.addBox(0F, 0F, -2F, 4, 12, 4);
      arm_right.setRotationPoint(4F, 0F, 0F);
      arm_right.setTextureSize(64, 32);
      arm_right.mirror = true;
      setRotation(arm_right, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    leg_right.render(f5);
    leg_left.render(f5);
    body.render(f5);
    head.render(f5);
    arm_left.render(f5);
    arm_right.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    	float f6 = (180F / (float)Math.PI);
    	this.leg_right.rotateAngleX = MathHelper.cos(f * 0.44F) *1.2F *f1;
     	this.leg_left.rotateAngleX = MathHelper.cos(f * 0.44F+(float)Math.PI) *1.2F *f1;
     	
     	this.arm_left.rotateAngleX = MathHelper.cos(f * 0.44F) *1.2F *f1;
     	this.arm_right.rotateAngleX = MathHelper.cos(f * 0.44F+(float)Math.PI) *1.2F *f1;
  }

}
